project:
  type: website
  output-dir: _site
  
bibliography: slides/DeceptiLabSlidesV4.bib
csl: apa.csl

website:
  title: "Deception Research in Psychology"
  
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: slides/DeceptiLabSlides.qmd
        text: Slides
        target: _blank

  sidebar: 
    background: primary
    style: floating
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: slides/DeceptiLabSlides.qmd
        text: Slides
        target: _blank
      

  page-footer:
    left: |
      <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a> • 
      Dr. Gordon Wright <br>
      A LittleMonkeyLab Caper
    right: |
      Made with ❤️ Quarto, RevealJS, and Zotero • © 2025

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    link-external-newwindow: true
    df-print: paged
    page-layout: article
    margin-left: 2em
    margin-right: 2em
  

metadata-files:
  - assets/_meta.yml

execute:
  freeze: auto

